# Generated by Django 3.1 on 2020-09-07 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='contents',
            field=models.TextField(default=django.utils.timezone.now, max_length=200, verbose_name='詳細'),
            preserve_default=False,
        ),
    ]
