# Generated by Django 3.1 on 2020-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contents',
            field=models.TextField(max_length=200, verbose_name='Contents'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
